apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: networkrequesthpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: userswebapp
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Pods
      pods:
        metric:
          name: pod_network_tx_bytes
        target:
          type: AverageValue
          averageValue: 2