apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: developers-k8s-role-binding
subjects:
  - kind: Group
    name: developer-aws-group
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: developers-k8s-cluster-role
  apiGroup: rbac.authorization.k8s.io