apiVersion: v1
kind: Service
metadata:
  name: shiftswebapp
  labels:
    app: shiftswebapp
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: shiftswebapp